-- CreateTable
CREATE TABLE "OPD" (
    "OPDID" SERIAL NOT NULL,
    "OPDNo" VARCHAR(250),
    "OPDDateTime" TIMESTAMP(3) NOT NULL,
    "PatientID" INTEGER NOT NULL,
    "TreatedByDoctorID" INTEGER NOT NULL,
    "IsFollowUpCase" BOOLEAN NOT NULL DEFAULT false,
    "RegistrationFee" DECIMAL(10,2) NOT NULL,
    "Description" VARCHAR(250),
    "UserID" INTEGER,
    "OLDOPDNo" VARCHAR(250),
    "Created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Modified" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OPD_pkey" PRIMARY KEY ("OPDID")
);

-- AddForeignKey
ALTER TABLE "OPD" ADD CONSTRAINT "OPD_PatientID_fkey" FOREIGN KEY ("PatientID") REFERENCES "Patient"("PatientID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OPD" ADD CONSTRAINT "OPD_TreatedByDoctorID_fkey" FOREIGN KEY ("TreatedByDoctorID") REFERENCES "Doctor"("DoctorID") ON DELETE RESTRICT ON UPDATE CASCADE;
